{% set name = "types-PyMySQL" %}
{% set version = "1.1.0.20250914" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: 69cc8d23e3c34d4d355af1a381964cae0f3264e948f63f9ef0f3e78d93e172d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/pymysql-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for PyMySQL
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
